server:
  port: 8123

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/momentours
    #    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    #    jdbc-url: jdbc:log4jdbc:mariadb://localhost:3306/momentours
    username: handjava
    password: handjava

  jpa:
    generate-ddl: false
    show-sql: true
    database: mysql
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: none
  application:
    name: momentours-user-service

logging:
  level:
    com:
      myhandjava:
        momentours-user: debug

mybatis:
  mapper-locations: classpath:/mappers/**/*.xml

token:
  expiration_time: 43200000
  secret: K0HHLFxls3IXU9tafT999JvEC3c80Dhy7qv41YyY99Pe1agCbJyiv558uBWHTQiYzRDdju9/CLtZltizLjGgSQ==

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka