server:
  port: 8123

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3307/momentours
    #    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    #    jdbc-url: jdbc:log4jdbc:mariadb://localhost:3306/momentours
    username: handjava
    password: handjava

  jpa:
    generate-ddl: false
    show-sql: true
    database: mysql
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: none
  application:
    name: momentours-user

logging:
  level:
    com:
      myhandjava:
        momentours-user: debug

mybatis:
  mapper-locations: classpath:/mappers/**/*.xml

# token config 설정
token:

  # 만료시간 설정(ms 단위)(현재 12시간)
  expiration_time: 43200000

  # HMAC secret 키 생성
  secret: K0HHLFxls3IXU9tafT999JvEC3c80Dhy7qv41YyY99Pe1agCbJyiv558uBWHTQiYzRDdju9/CLtZltizLjGgSQ==